### ISSUE TITLE
Issue with Pixinsight.

### ISSUE THREAD

**Issue by tlkw79** [AstroDeepSky/GraXpert4PixInsight#5]
Hi,

I am having this issue after upgrading to GraXpert 2.1.0.

run --execute-mode=auto "/opt/PixInsight/src/scripts/PixGraXpert/GraXpert.js"

Processing script file: /opt/PixInsight/src/scripts/PixGraXpert/GraXpert.js

GraXpert load parameters: 
GraXpert script for PixInsight version v1.0.0-beta.3 (2023-12-22 11:17)
Please note you are using a Beta version!
THIS VERSION REQUIRES GraXpert BETA v2.0.3test or higher.
THIS VERSION IS NOT COMPATIBLE WITH GraXpert v2.0.2.
Parameters Ok

Writing file:
/tmp/Pix.xisf
Writing image: w=4952 h=3288 n=3 RGB Float32
55 FITS keyword(s) embedded
Display function parameters embedded
ICC profile embedded: 'sRGB IEC61966-2.1', 3024 bytes

Run GraXpert: 
Exec: /usr/bin/GraXpert
Input:  /tmp/Pix.xisf
Output: /tmp/Pix_GraXpert.xisf
AI model: Default
Smoothing: 0.5
Correction: Subtraction
Status: File not found
File /tmp/Pix_GraXpert.xisf not found

GraXpert output: 
2023-12-30 17:22:21,071 MainProcess root ERROR    usage: GraXpert [-h] [-ai_version [AI_VERSION]]
2023-12-30 17:22:21,072 MainProcess root ERROR                    [-correction [{Subtraction,Division}]]
2023-12-30 17:22:21,072 MainProcess root ERROR                    [-smoothing [SMOOTHING]]
2023-12-30 17:22:21,072 MainProcess root ERROR                    filename
2023-12-30 17:22:21,072 MainProcess root ERROR    GraXpert: error: unrecognized arguments: -cli

Please ensure you have GraXpert version 2.0.3 or higher

**Comment by AstroDeepSky** [comment]
Hello,
Error message "unrecognized arguments: -cli" shows that last GraXpert 2.1.0 does not include changes introduced in versions 2.0.3test.
I'll do more tests this evening and provide a script compatible with this version.

**Comment by AstroDeepSky** [comment]
I have reported 2 issues to GraXpert team:

- https://github.com/Steffenhir/GraXpert/issues/112
- https://github.com/Steffenhir/GraXpert/issues/113

If you need export of background in PixInsight, I suggest you to use GraXpert 2.0.3test with GraXpert4PixInsight v1.0.0-beta.3.
Else, use official GraXpert v2.0.2 with GraXpert4PixInsight v0.0.7.

I recommend first option. Indeed, GraXpert 2.0.3test introduce a minimal set of changes compare to official v2.0.2.
I'll update this case when I'll get more information from GraXpert team.

**Comment by AstroDeepSky** [comment]
GraXpert team is working on fixes. A new v2.1.1 should come soon.
I'll keep you posted.

**Comment by AstroDeepSky** [comment]
GraXpert PreRelease 2.1.1 available and tested Ok
https://github.com/Steffenhir/GraXpert/releases/tag/2.1.1

**Comment by AstroDeepSky** [comment]
I let you confirm before closure.

**Comment by tlkw79** [comment]
Thanks and everything looks good now.

**Comment by AstroDeepSky** [comment]
Thanks for confirmation.
